#!/bin/csh
echo "pro/gam0105_1.pro"
bin/bap_search2 pro/gam0105_1.pro one no
echo ""
echo "pro/gam0105_2.pro"
bin/bap_search2 pro/gam0105_2.pro one no
echo ""
echo "pro/gam0105_3.pro"
bin/bap_search2 pro/gam0105_3.pro one no
echo ""
echo "pro/gam0107_1.pro"
bin/bap_search2 pro/gam0107_1.pro one no
echo ""
echo "pro/gam0107_2.pro"
bin/bap_search2 pro/gam0107_2.pro one no
echo ""
echo "pro/gam0107_3.pro"
bin/bap_search2 pro/gam0107_3.pro one no
echo ""
echo "pro/gam0107_4.pro"
bin/bap_search2 pro/gam0107_4.pro one no
echo ""
echo "pro/gam0107_5.pro"
bin/bap_search2 pro/gam0107_5.pro one no
echo ""
echo "pro/gam0107_6.pro"
bin/bap_search2 pro/gam0107_6.pro one no
echo ""
echo "pro/gam0108_1.pro"
bin/bap_search2 pro/gam0108_1.pro one no
echo ""
echo "pro/gam0108_2.pro"
bin/bap_search2 pro/gam0108_2.pro one no
echo ""
echo "pro/gam0108_3.pro"
bin/bap_search2 pro/gam0108_3.pro one no
echo ""
echo "pro/gam0108_4.pro"
bin/bap_search2 pro/gam0108_4.pro one no
echo ""
echo "pro/gam0108_5.pro"
bin/bap_search2 pro/gam0108_5.pro one no
echo ""
echo "pro/gam0108_6.pro"
bin/bap_search2 pro/gam0108_6.pro one no
echo ""
echo "pro/gam0109_1.pro"
bin/bap_search2 pro/gam0109_1.pro one no
echo ""
echo "pro/gam0109_2.pro"
bin/bap_search2 pro/gam0109_2.pro one no
echo ""
echo "pro/gam0109_3.pro"
bin/bap_search2 pro/gam0109_3.pro one no
echo ""
echo "pro/gam0109_4.pro"
bin/bap_search2 pro/gam0109_4.pro one no
echo ""
echo "pro/gam0109_5.pro"
bin/bap_search2 pro/gam0109_5.pro one no
echo ""
echo "pro/gam0109_6.pro"
bin/bap_search2 pro/gam0109_6.pro one no
echo ""
echo "pro/ftez1.pro"
bin/bap_search2 pro/ftez1.pro one no
echo ""
echo "pro/ftez2.pro"
bin/bap_search2 pro/ftez2.pro one no
echo ""
echo "pro/ftez3.pro"
bin/bap_search2 pro/ftez3.pro one no
echo ""
echo "pro/ftez4.pro"
bin/bap_search2 pro/ftez4.pro one no
echo ""
echo "pro/ftez5.pro"
bin/bap_search2 pro/ftez5.pro one no
echo ""
echo "pro/ftez6.pro"
bin/bap_search2 pro/ftez6.pro one no
echo ""
echo "pro/ftez7.pro"
bin/bap_search2 pro/ftez7.pro one no
echo ""
echo "pro/ftez8.pro"
bin/bap_search2 pro/ftez8.pro one no
echo ""
echo "pro/ftez9.pro"
bin/bap_search2 pro/ftez9.pro one no
echo ""
echo "pro/ftez10.pro"
bin/bap_search2 pro/ftez10.pro one no
echo ""
echo "pro/ftin1.pro"
bin/bap_search2 pro/ftin1.pro one no
echo ""
echo "pro/ftin2.pro"
bin/bap_search2 pro/ftin2.pro one no
echo ""
echo "pro/ftin3.pro"
bin/bap_search2 pro/ftin3.pro one no
echo ""
echo "pro/ftin4.pro"
bin/bap_search2 pro/ftin4.pro one no
echo ""
echo "pro/ftin5.pro"
bin/bap_search2 pro/ftin5.pro one no
echo ""
echo "pro/ftin6.pro"
bin/bap_search2 pro/ftin6.pro one no
echo ""
echo "pro/ftin7.pro"
bin/bap_search2 pro/ftin7.pro one no
echo ""
echo "pro/ftin8.pro"
bin/bap_search2 pro/ftin8.pro one no
echo ""
echo "pro/ftin9.pro"
bin/bap_search2 pro/ftin9.pro one no
echo ""
echo "pro/ftin10.pro"
bin/bap_search2 pro/ftin10.pro one no
echo ""
echo "pro/ftha1.pro"
bin/bap_search2 pro/ftha1.pro one no
echo ""
echo "pro/ftha2.pro"
bin/bap_search2 pro/ftha2.pro one no
echo ""
echo "pro/ftha3.pro"
bin/bap_search2 pro/ftha3.pro one no
echo ""
echo "pro/ftha4.pro"
bin/bap_search2 pro/ftha4.pro one no
echo ""
echo "pro/ftha5.pro"
bin/bap_search2 pro/ftha5.pro one no
echo ""
echo "pro/ftha6.pro"
bin/bap_search2 pro/ftha6.pro one no
echo ""
echo "pro/ftha7.pro"
bin/bap_search2 pro/ftha7.pro one no
echo ""
echo "pro/ftha8.pro"
bin/bap_search2 pro/ftha8.pro one no
echo ""
echo "pro/ftha9.pro"
bin/bap_search2 pro/ftha9.pro one no
echo ""
echo "pro/ftha10.pro"
bin/bap_search2 pro/ftha10.pro one no
echo ""
echo "pro/ftex1.pro"
bin/bap_search2 pro/ftex1.pro one no
echo ""
echo "pro/ftex2.pro"
bin/bap_search2 pro/ftex2.pro one no
echo ""
echo "pro/ftex3.pro"
bin/bap_search2 pro/ftex3.pro one no
echo ""
echo "pro/ftex4.pro"
bin/bap_search2 pro/ftex4.pro one no
echo ""
echo "pro/ftex5.pro"
bin/bap_search2 pro/ftex5.pro one no
echo ""
echo "pro/ftex6.pro"
bin/bap_search2 pro/ftex6.pro one no
echo ""
echo "pro/ftex7.pro"
bin/bap_search2 pro/ftex7.pro one no
echo ""
echo "pro/ftex8.pro"
bin/bap_search2 pro/ftex8.pro one no
echo ""
echo "pro/ftex9.pro"
bin/bap_search2 pro/ftex9.pro one no
echo ""
echo "pro/ftex10.pro"
bin/bap_search2 pro/ftex10.pro one no
